spring:
    profiles:
      active: dev
    thymeleaf:
      cache: false
      mode: HTML5
    redis:
      cluster:
        nodes: 192.168.1.4:6379,192.168.1.5:6379

server:
    port: 8888

---
spring:
    profiles: dev
    thymeleaf:
      cache: false
      mode: HTML5
      check-template: false
server:
  port: 8180
cassandra:
  servers: localhost
  port: 9042
---
spring:
    profiles: prod
server:
  port: 8888
cassandra:
  servers: 192.168.1.4
  port: 9042
