spring:
    profiles:
      active: dev
    thymeleaf:
      cache: false
      mode: HTML5
server:
    port: 8888
---
spring:
    profiles: dev
server:
  port: 8180
cassandra:
  servers: localhost
  port: 9042
---
spring:
    profiles: prod
server:
  port: 8888
cassandra:
  servers: 192.168.1.4
  port: 9042